### ISSUE TITLE
Malicious ads on pedump.me

### ISSUE THREAD

**Issue by Sonic-The-Hedgehog-LNK1123** [zed-0xff/pedump#11]
I fully understand you want to generate some ad revenue, but the current crappy ad-service you're using on pedump.me is **unacceptable.** This hurts the experience of your visitors, and some may even **report your site as MALICIOUS.** You are hurting the reputation of your own site.

The affected ads include:

* Offensive / sexual ads that are commonly associated with websites that provide illegal downloads.
* Even worse: Ads that contain **automatic redirects to sites with fake news, porn and SCAMs!**

You should **remove the ads** and use a **reputable** ad-service.

Below are two screenshots to websites I got redirected to from pedump.me **without** clicking on any ads:

![Screenshot_2020-01-24 Screenshot](https://user-images.githubusercontent.com/46045820/73079227-1ed4dc00-3ec4-11ea-9b48-2bb2a12f46d1.png)

Fake Microsoft tech support scam

 

![Screenshot_2020-01-24 Security Alert ](https://user-images.githubusercontent.com/46045820/73079228-1ed4dc00-3ec4-11ea-934b-070b1aa83fc1.png)

Fake antivirus scanner

**Comment by FuccDucc** [comment]
yeah, I don't think they care, considering it's still the case months after you wrote this.

The first time i ever visited this site i got faced with automatic redirect, randomly out of the blue, while looking at a certain submitted file. It just decided that I had to stop reading it (the entire pedump site went away, ads loaded in the same tab and I couldn't navigate back because the ads had a redirection "protection" that would revert going back) and face some malicious ads. You can see these ads in my history:

![image](https://user-images.githubusercontent.com/61570793/84000945-f24ac980-a965-11ea-8ae7-05df7c7c1848.png)

And for example, 1 of them wasn't just a scam, but a scam that impersonated a reputable news website from the Netherlands (my country), the news medium is called "NOS" and you can see how the ad faked it below:
![image](https://user-images.githubusercontent.com/61570793/84001013-18706980-a966-11ea-937d-a3f4f7640d72.png)

The fake news site contains a known "social engineering" scam campaign, for which criminals impersonate national celebrities and mainstream news mediums (copy their entire site design), and the "NOS" fake ad above contains this in the page it served me:

![image](https://user-images.githubusercontent.com/61570793/84001304-9af92900-a966-11ea-93e7-f43e45a4adc6.png) - btw, i archived the full version of the specific linked page it served me, here if needed to confirm its scam: [https://web.archive.org/web/20200608065845/https://bitcoinnews24.me/nl/?_subid=2iq7sfn503f18&_token=uuid_2iq7sfn503f18_2iq7sfn503f185edddef5acb3a1.32952288](https://web.archive.org/web/20200608065845/https://bitcoinnews24.me/nl/?_subid=2iq7sfn503f18&_token=uuid_2iq7sfn503f18_2iq7sfn503f185edddef5acb3a1.32952288) 

It is the beginning of such a scam article. If you're from Holland you might know about this scam campaign (where cybercriminals use affiliate advertisement platforms, and sites like you, PEdump, in this case fall for it through a bad affiliate platform) because the 'real' mainstream media dedicated a bunch of articles to it already, such as: [https://nos.nl/artikel/2280062-veel-schade-door-bitcoin-advertenties-met-nepuitspraken-bn-ers.html](https://nos.nl/artikel/2280062-veel-schade-door-bitcoin-advertenties-met-nepuitspraken-bn-ers.html) (but they keep using different people and sites to impersonate - they are known to make millions of euro's of profit from their victims, and other media published about the scam campaigns as well).

So it's clear that these scam ads are currently being served by PEdump site, aware or unaware. I hope unaware and that it can be resolved soon.. if you get paid more for being aware that there's bad adds, then shame on you. If PEdump administrators won't do anything with this, then you are as guilty, a cog in the system that is causing people to fall for scams.

**Comment by Sonic-The-Hedgehog-LNK1123** [comment]
@FuccDucc That NOS page you posted was the exact page I was referring to with the term "fake news" in my original post! which is, as you said, the start of a Bitcoin scam. Also, creating a scam page like that is trivial:

1. save the legit webpage 
2. replace the text
3. upload the page to your scam site
4. done!

I've even found out after a lot of analysis, the ad network "AdsTerra" is serving the ads. and, after searching the web for it, I got a lot of results from publishers that care about their visitors to tell others to avoid AdsTerra like the plague. So, they have a very bad reputation, but for some reason they still exist.

If you want to use the PEdump site without interruption, add the following lines to your **hosts file:**
```
        127.0.0.1       ampugi334f.com
        127.0.0.1       www.ampugi334f.com
        127.0.0.1       hiprofitnetworks.com
        127.0.0.1       madcpms.com
        127.0.0.1       www.hiprofitnetworks.com
        127.0.0.1       www.madcpms.com
```
That should block the ads and redirects caused by them completely for now.

**Comment by FuccDucc** [comment]
To be honest, i think that @zed-0xff culpable and that we might need to start reporting him, and his website (pedump.me) to the appropiate blacklists and authorities (as he's participating in scamming schemes, by knowingly contracting a bad advertisement merchant, or otherwise neglecting his duty to stop working with malicious/scammer ads platforms as soon he takes receipt of reports like this issue is). 

The fact that he doesn't care makes me want to start playing it that way, knowing that his site has significant traffic and therefore he's opening the door to harm a lot of people's interests and online browsing safety.

**Comment by zed-0xff** [comment]
Removed all the ads for now.
Sorry guys, I just wanted a couple of bucks to pay for pedump hosting.
This was the ads from adsterra.com, and they had not shown any malicious content on my PC, I think they use geotargeting or smth like this.
btw all I got from this is just $10 for 5 months.
For some reason I received github email notification of this issue only today, I had searched my inbox and no previous comments toggled the notificaton, only when @FuccDucc mentioned my nickname.
Sorry again and no ads from now.

PS: First of all, I tried google ads, but they refused my site because "its machine-generated, and has no unique interesting content"

**Comment by Sonic-The-Hedgehog-LNK1123** [comment]
@zed-0xff You already had a donate button on some pages of the site, you should put that on **all** pages. And, if you need more money for hosting, **let your visitors know**. a lot of websites put a clear notification on all pages if more money for hosting is needed.

If you search the web for "adsterra malware" you'll see they have a bad reputation.

Also, **Google needs their ad policy fixed!** most publishers that tried AdsTerra are the ones that were refused by Google.

**Comment by FuccDucc** [comment]
> Removed all the ads for now.

> For some reason I received github email notification of this issue only today, I had searched my inbox and no previous comments toggled the notificaton, only when @FuccDucc mentioned my nickname.

Thanks for resolving it, and okay then it's understandable.. don't mind my rude wording.

**Comment by Sonic-The-Hedgehog-LNK1123** [comment]
The ads are indeed gone now, So I'll close this.
